version: '3.5'
services:
  fuseki:
    image: stain/jena-fuseki:3.10.0
    container_name: fuseki_aurba
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build: middleware
    container_name: middleware_aurba
    depends_on:
      - fuseki
    volumes:
      - ./middleware/:/app
      - ./../semapps:/semapps
      - ./data/fuseki/backups:/app/fuseki-backups # Needed to backup fuseki datasets
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki_aurba:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=http://localhost:3000/
      - SEMAPPS_BACKUP_FUSEKI_DATASETS_PATH=/app/fuseki-backups
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "yarn install && npm run devwithlink"

  frontend:
    build: frontend
    container_name: frontend_aurba
    volumes:
      - ./frontend:/app
      - ./../semapps:/semapps
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_MAPBOX_ACCESS_TOKEN=
      - PORT=5000
    depends_on:
      - middleware
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "yarn install && npm run startwithlink"
